spring.application.name=API-USUARIO
server.port=9000
spring.datasource.url=jdbc:sqlite:Usuario.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true